apiVersion: v2
name: mlflow
description: |
  [MLFlow](https://mlflow.org/) is an open source platform specialized in tracking ML experiments, and packaging and deploying ML models.
  Forked from https://github.com/larribas/helm-charts/
home: "https://github.com/dingobar/helm-charts/tree/master/mlflow"
maintainers:
  - url: https://github.com/dingobar/
    name: dingobar
type: application
version: 1.0.5
appVersion: 1.15.2
